Functional professor vertical
michiganhackers/class-review-backend pull request #5
Opened 2019-06-23 21:45 UTC by Yand1

2019-06-23 22:29 UTC, christopherhafke requested changes
Refactor to implement a professors table

2019-06-24 00:43 UTC, gmudel commented
Since we're going by professor's uniqname now, could you change all instances of professor_name in reviews to professor_uniqname?

2019-07-07 21:22 UTC, christopherhafke requested changes
A few changes, mostly regarding pointers, to be made

2019-07-07 21:22 UTC, christopherhafke commented on repositories/professor_repository.go
> +func (pr *ProfessorRepository) GetAllProfessors() (*[]models.Professor, error) {
You don't need pointers-to-slices, since slices already act as pointers to the underlying data

2019-07-07 21:22 UTC, christopherhafke commented on repositories/professor_repository.go
> +									 WHERE professor_uniqname = :professor_uniqname`, *professorInput)
I believe NamedExec expects a pointer to a struct as its second argument so that it can modify the struct it's given

2019-07-07 22:15 UTC, christopherhafke reviewed
Looks good to me

2019-07-07 22:16 UTC, christopherhafke approved these changes

2019-07-07 22:17 UTC, merged